version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: my-next-app:prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: always