name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t nextjs-app:latest -f Dockerfile.prod .

      - name: Save image to tar file
        run: docker save nextjs-app:latest -o nextjs-app.tar

      - name: Send Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "nextjs-app.tar"
          target: "~/nextjs-app.tar"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker stop nextjs-app || true
            docker rm nextjs-app || true
            docker load -i ~/nextjs-app.tar
            docker run -d --name nextjs-app -p 80:3000 nextjs-app:latest